
USE ROLE ACCOUNTADMIN;
SELECT SYSTEM$GET_SNOWFLAKE_PLATFORM_INFO();

create or replace storage integration s3_int
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE 
  STORAGE_AWS_ROLE_ARN = 'arn::iam::{YOUR_AWS_ACCOUNT_ID}:role/snowflake_access'
  STORAGE_ALLOWED_LOCATIONS = ('s3://kinesis-bench-de')
   COMMENT = 'This an optional comment' ;

DESC integration s3_int;

CREATE OR REPLACE stage DEMO_DATABASE.PUBLIC.WIKIPEDIA url = "s3://kinesis-bench-de"
STORAGE_INTEGRATION = s3_int

list @DEMO_DATABASE.PUBLIC.WIKIPEDIA;

COPY INTO WIKIPEDIA
FROM @DEMO_DATABASE.PUBLIC.WIKIPEDIA
FILE_FORMAT = (TYPE = 'PARQUET')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

SELECT * FROM WIKIPEDIA